name: mockapi
version: "0.0.1"
about: Creates API for testing from command line
author: etopiei - lj343@icloud.com

subcommands:
  - start:
    about: Start server
    args:
      - port:
          short: p
          takes_value: true
          help: Sets the port of the servername
      - servername:
          required: true
          help: The servername to start
  - delete:
    about: Delete response from server
    args: 
      - servername:
          required: true
          help: The name of the server to delete response from
      - route_name:
          required: true
          help: The name of the response to delete
  - create:
    about: Creates a new server
    args:
      - servername:
          help: The servername to create
          required: true
  - new:
    about: Creates a new response
    args:
      - type:
        help: Sets the type, GET or POST (default is GET)
        short: t
        takes_value: true
      - response:
        help: Sets the type of response, default is text/plain, application/json, text/csv and application/xml are also supported
        short: r
        takes_value: true
      - servername:
        help: The name of the server to create a response for
        required: true
      - routename: 
        help: The name of the response to create
        required: true
  - edit:
    about: Edits a response
    args:
      - editor:
        help: Sets the editor to edit the response (default is nano) vi and emacs also available
        short: e
        takes_value: true
      - servername:
        help: The name of the server to edit response of
        required: true
      - routename: 
        help: The name of the response to edit
        required: true